### ISSUE TITLE
1.3.0 ImportError: libpq-a407f694.so.5.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by juanvisoler** [AbhimanyuHK/aws-psycopg2#10]
Hello,

after upgrading the library to 1.3.0 we got this error:

`Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from analytics.data_connections import (
  File "/mnt3/yarn/usercache/hadoop/appcache/application_1655930109200_0001/container_1655930109200_0001_01_000001/analytics-09626d7-py3.7.egg/analytics/data_connections.py", line 6, in <module>
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq-a407f694.so.5.12: cannot open shared object file: No such file or directory`

Using `python 3.7` and `emr-6.4.0`.

The workaround was to revert to `1.2.1`.

Thanks

**Comment by AbhimanyuHK** [comment]
Hi @juanvisoler .

Try the latest build https://pypi.org/project/aws-psycopg2/1.3.8/
